# Generated by Django 6.0 on 2025-12-06 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('idagenda', models.AutoField(primary_key=True, serialize=False)),
                ('data_consulta', models.DateField()),
                ('hora_consulta', models.TimeField()),
                ('motivo', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.medico')),
            ],
        ),
    ]
