# Generated by Django 6.0 on 2025-12-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('data_de_nascimento', models.DateField()),
                ('endereço', models.CharField(max_length=200)),
            ],
        ),
    ]
